language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database recipe_app;' -U postgres

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
